version: 0.2

phases:
  install:
    commands:
      - echo "Setting up OWASP Dependency-Check..."
      - wget https://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
      - unzip dependency-check-12.1.0-release.zip
      - mv dependency-check /opt/dependency-check
      - /opt/dependency-check/bin/dependency-check.sh --version

  build:  # ✅ Replaced 'owaspstage' with 'build' (a valid phase)
    commands:
      - echo "Checking NVD cache directory..."
      - mkdir -p /opt/nvd-cache  # Ensure cache directory exists
      - ls -lah /opt/nvd-cache  # Verify if cache is restored

      - echo "Running OWASP Dependency-Check..."
      - /opt/dependency-check/bin/dependency-check.sh --project "Django Project" --scan "$CODEBUILD_SRC_DIR/" --out ./dependency-check-report --data "/opt/nvd-cache" --log dependency-check.log

      - echo "OWASP Dependency-Check completed"

artifacts:
  files:
    - dependency-check-report/*
    - dependency-check.log

cache:
  paths:
    - '/opt/nvd-cache/**/*'  # Cache the NVD data directory across builds
