# Generated by Django 2.1.15 on 2025-03-22 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('urgency', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('category', models.CharField(choices=[('Supplies', 'Supplies'), ('Equipment', 'Equipment'), ('Food', 'Food'), ('Other', 'Other')], default='Supplies', max_length=50)),
                ('department_section', models.CharField(choices=[('Kitchen', 'Kitchen'), ('Bar', 'Bar'), ('Dining', 'Dining'), ('General', 'General')], default='General', max_length=50)),
                ('reason', models.CharField(choices=[('Running Low', 'Running Low'), ('Broken', 'Broken'), ('New Event', 'New Event'), ('Other', 'Other')], default='Running Low', max_length=50)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
